### ISSUE TITLE
[FEAT] iOS 7차 과제

### ISSUE THREAD

**Issue by hellozo0** [29th-WE-SOPT-iOS-Part/AnHyeonJu#11]
## 📌  Feature Issue
데이터 연결 심화와 UIGestureRecognizer

## 📝  To-do
- [x] imageView에 tap gesture recognizer action연결
- [x] imageView가 tap 되었을 때, 화면전환(present)
- [x] 화면전환할때 [imageView, title, 조회수&업로드 시간] 데이터 전달
- [x] 화면전환View에 버튼 누르면 dismiss
