### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by hellozo0** [29th-WE-SOPT-iOS-Part/AnHyeonJu#7]
## 📌 Feature Issue

3주차 과제는  TableView와 CollectionView를 활용하여 Youtube 홈 화면 구성하기 입니다!

## 📝 To-do

▶️ 상단부분 
- [x]  UI구성 및 AutoLayout

▶️ Video 영역 TableView Cell 구현하기
- [x]  Xib 파일로 만들기
- [x]  UI구성 및 AutoLayout

▶️ Shorts 영역 CollectionView cell 구현하기
- [x]  Xib 파일로 만들기
- [x]  UI구성 및 AutoLayout

🔥도전과제
- [x]  태그 영역 UI구성 및 AutoLayout
- [x]  text 길이에 따라 cell 크기가 다르게 구현
