### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by hellozo0** [29th-WE-SOPT-iOS-Part/AnHyeonJu#9]
## 📌  Feature Issue

4주차 과제는 처음만들었던 로그인 회원가입에 실제 API를 붙여보기입니다!

## 📝  To-do
▶️ 프로필 화면전환
- [x] 시작 스토리보드 변경
- [x] 프로필 클릭시 로그인 flow로 화면전환

▶️ 로그인
- [x] 다음 버튼 클릭 시 서버 통신을 하고 alert 띄우기 
- [x] 존재하지 않는 회원 alert
- [x] 필요한 값이 없는 alert
- [x] 로그인 성공 alert
- [x] 로그인 성공 alert의 확인 클릭시 확인화면으로 전환

▶️ 회원가입
- [x] 다음 버튼 클릭 시 서버 통신을 하고 alert 띄우기 
- [x] 이미 사용중인 이메일 alert
- [x] 필요한 값이 없는 alert
- [x] 회원가입 성공 alert
- [x]  회원가입 성공 alert의 확인 클릭시 확인화면으로 전환

🔥도전과제
- [x] 로그인할 때 받는 결과값중 name값을 UserDefaults에 저장한 후 확인화면에 띄워주기
